name: galaxy-training-material-stats
channels:
- bioconda
- r
- conda-forge
- defaults
dependencies:
- dropbox=5.2.1=py36_0
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- pysftp=0.2.9=py36_0
- snakemake=3.13.2=py36_0
- urllib3=1.12=py36_0
- flake8-import-order=0.12=py36_0
- pep8-naming=0.4.1=py36_0
- pygithub=1.34=py36_0
- pyjwt=1.5.0=py36_0
- asn1crypto=0.22.0=py36_0
- cffi=1.10.0=py36_0
- cryptography=1.8.1=py36_0
- cycler=0.10.0=py36_0
- docutils=0.13.1=py36_0
- flake8=3.3.0=py36_0
- freetype=2.5.5=2
- icu=54.1=0
- idna=2.5=py36_0
- jbig=2.1=0
- jpeg=9b=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- matplotlib=2.0.2=np113py36_0
- mccabe=0.6.1=py36_0
- mkl=2017.0.1=0
- numpy=1.13.0=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- pandas=0.20.2=np113py36_0
- paramiko=2.1.2=py36_0
- pillow=4.1.1=py36_0
- pip=9.0.1=py36_1
- psutil=5.2.2=py36_0
- pyasn1=0.2.3=py36_0
- pycodestyle=2.3.1=py36_0
- pycparser=2.17=py36_0
- pyflakes=1.5.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- qt=5.6.2=2
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- wrapt=1.10.10=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
